fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "mysql": "git://github.com/puppetlabs/puppetlabs-mysql.git"
    "apt":
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: '2.2.2'
    "firewall": "git://github.com/puppetlabs/puppetlabs-firewall.git"
    "xinetd": "git://github.com/puppetlabs/puppetlabs-xinetd.git"
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core"
      puppet_version: ">= 6.0.0"
