---
.puppet-lint.rc:
  required:
    - '--no-140chars-check'

spec/spec_helper.rb:
  hiera_config: spec/fixtures/hiera.yaml
  coverage_report: true

spec/default_facts.yml:
  extra_facts:
    root_home: /root
    fqdn: localhost
