---
name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        puppet_version: [6, 7]

    name: Check / Puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Run pdk validate
        uses: puppets-epic-show-theatre/action-pdk-validate@31b5407676af16b690b2b8c54c0767af72fcc34f
        with:
          puppet-version: ${{ matrix.puppet_version }}

      - name: Run pdk test unit
        uses: puppets-epic-show-theatre/action-pdk-test-unit@193987acba9977d1825fefbcbaf8d02d6af78106
        with:
          puppet-version: ${{ matrix.puppet_version }}

  acceptance:
    strategy:
      fail-fast: false
      matrix:
        os: ['el7']
        puppet_version: [7]
        #puppet_version: [6, 7]
        vendor_type: ['percona']
        #vendor_type: ['codership', 'mariadb', 'percona']

    name: Acceptance / ${{ matrix.os }} / ${{ matrix.vendor_type }} / Puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-20.04
    needs:
      - check

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Run Litmus
        env:
          VENDOR_TYPE: ${{ matrix.vendor_type }}
        run: |
          bundle exec rake 'litmus:provision_list[travis_${{ matrix.os }}]'
          bundle exec rake 'litmus:install_agent[puppet${{ matrix.puppet_version }}]'
          bundle exec rake litmus:install_module
          bundle exec rake litmus:acceptance:parallel
